baseURL: "/"
title: Ritesh Sonawane
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: 
  title: Ritesh Sonawane
  description: "Portfolio Website"
  keywords: [Blog, Portfolio, PaperMod,Devops,Golang,Cloud Native, kubernetes]
  author: Me
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/favicon-16x16.png"

  label:
    text: "Ritesh"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Ritesh Sonawane
    subtitle: "Hey î†§, I'm a Ritesh Sonawane an Associate SRE at CloudRaft. I love to share my learnings. Check my blogs if you are interested in DevOps, SRE and Cloud native"
    imageUrl: "/profile-photo.png"
    imageWidth: 220
    imageHeight: 220
    imageTitle: profile-photo
    buttons:
      - name: Blogs
        url: "https://pidoku.co.in"
  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "Golang and Devops Engineer"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/RiteshS14112760"
    - name: github
      url: "https://github.com/riteshsonawane1372"
    - name: linkedin
      url: "https://www.linkedin.com/in/ritesh-sonawane-794b6a226/"

  analytics:
    google:
      SiteVerificationTag: "ritesh sonawane1372"
    bing:
      SiteVerificationTag: "ritesh sonawane"
    yandex:
      SiteVerificationTag: "ritesh sonawane"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/riteshsonawane1372"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
# menu:
#   main:
    # - identifier: categories
    #   name: remote-jobs
    #   url: "https://remote-jobs.riteshsonawane.com"
    #   weight: 10
    # - identifier: categories
    #   name: Blog
    #   url: "https://blog.riteshsonawane.com/"
    #   weight: 10
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: true
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
